import { VectorStore } from '@/infrastructure/vector-store';
import { RAGManager } from '@/infrastructure/rag-manager';
import { EmbeddingManager } from '@/infrastructure/embedding-manager';
import type { RAGConfig } from '@/types';

jest.mock('@/infrastructure/embedding-manager', () => ({
	EmbeddingManager: {
		generateEmbedding: jest.fn(),
		getDefaultEmbeddingModel: jest.fn(() => ({ id: 'test-embedding' })),
		cleanup: jest.fn(),
	},
}));

const makeConfig = (overrides: Partial<RAGConfig> = {}): RAGConfig => ({
	enabled: true,
	chunkSize: 20,
	chunkOverlap: 0,
	topK: 5,
	embeddingModel: 'test-embedding',
	vectorStore: 'disk',
	embedChangedFiles: false,
	similarityThreshold: 0,
	relevanceScoreWeight: 0.5,
	searchType: 'semantic',
	maxTokensPerChunk: 1000,
	minChunkSize: 1,
	enableCompression: false,
	embeddingBatchSize: 10,
	indexingMode: 'manual',
	excludeFolders: [],
	includeFileTypes: ['md'],
	excludeFileTypes: [],
	contextWindowLimit: 2000,
	enableSemanticCaching: false,
	cacheSize: 50,
	filterByTag: [],
	excludeByTag: [],
	chunkingStrategy: 'paragraph',
	reRankingEnabled: false,
	reRankingModel: '',
	enableGradingThreshold: false,
	graderModelSource: 'chat',
	graderParallelProcessing: 3,
	...overrides,
});

const makeApp = (content = '') => {
	const adapter = {
		exists: jest.fn(async () => true),
		read: jest.fn(async () => {
			throw new Error('missing');
		}),
		write: jest.fn(async () => undefined),
	};
	return {
		vault: {
			adapter,
			read: jest.fn(async () => content),
			getMarkdownFiles: jest.fn(() => []),
			on: jest.fn(),
			off: jest.fn(),
		},
	};
};

describe('VectorStore', () => {
	beforeEach(() => {
		(EmbeddingManager.generateEmbedding as jest.Mock).mockReset();
		(EmbeddingManager.generateEmbedding as jest.Mock).mockImplementation(async () => [1, 0, 0]);
	});

	it('resolves addFile only after every scheduled chunk batch has been indexed and saved', async () => {
		const paragraphs = Array.from({ length: 25 }, (_, i) => `paragraph-${i}`).join('\n\n');
		const app = makeApp(paragraphs);
		const store = new VectorStore(app as any, [{ provider: 'openai', apiKey: 'k' }] as any);

		await store.addFile({
			path: 'notes/large.md',
			basename: 'large',
			stat: { mtime: 123 },
		} as any, makeConfig());

		expect(store.getStoredChunks()).toHaveLength(25);
		expect(app.vault.adapter.write).toHaveBeenCalledTimes(1);
	});

	it('removeFile drops only the matching file\'s chunks and persists', async () => {
		const app = makeApp('alpha\n\nbeta');
		const store = new VectorStore(app as any, [{ provider: 'openai', apiKey: 'k' }] as any);
		await store.addFile({ path: 'a.md', basename: 'a', stat: { mtime: 1 } } as any, makeConfig());
		await store.addFile({ path: 'b.md', basename: 'b', stat: { mtime: 1 } } as any, makeConfig());
		const before = store.getStoredChunks().length;

		const removed = await store.removeFile('a.md');

		expect(removed).toBeGreaterThan(0);
		expect(store.getStoredChunks().every((c) => c.metadata.path === 'b.md')).toBe(true);
		expect(store.getStoredChunks().length).toBe(before - removed);
	});

	it('renameFile re-keys chunk ids + metadata path without re-embedding', async () => {
		const app = makeApp('alpha\n\nbeta');
		const store = new VectorStore(app as any, [{ provider: 'openai', apiKey: 'k' }] as any);
		await store.addFile({ path: 'old.md', basename: 'old', stat: { mtime: 1 } } as any, makeConfig());
		(EmbeddingManager.generateEmbedding as jest.Mock).mockClear();

		const renamed = await store.renameFile('old.md', 'new.md');

		expect(renamed).toBeGreaterThan(0);
		const chunks = store.getStoredChunks();
		expect(chunks.every((c) => c.metadata.path === 'new.md')).toBe(true);
		expect(chunks.every((c) => c.id.startsWith('new.md-'))).toBe(true);
		// No new embeddings were generated by the rename.
		expect(EmbeddingManager.generateEmbedding).not.toHaveBeenCalled();
	});
});

describe('RAGManager', () => {
	it('does not clear the existing vector store when RAG is disabled through config', async () => {
		const manager = new RAGManager(makeApp() as any, makeConfig(), [{ provider: 'openai', apiKey: 'k' }] as any);
		const vectorStore = (manager as any).vectorStore;
		vectorStore.clear = jest.fn();

		manager.updateConfig(makeConfig({ enabled: false }));

		expect(vectorStore.clear).not.toHaveBeenCalled();
	});

	it('removeFile / renameFile delegate to the vector store when enabled', async () => {
		const manager = new RAGManager(makeApp() as any, makeConfig(), [{ provider: 'openai', apiKey: 'k' }] as any);
		const vectorStore = (manager as any).vectorStore;
		vectorStore.removeFile = jest.fn(async () => 3);
		vectorStore.renameFile = jest.fn(async () => 2);

		expect(await manager.removeFile('x.md')).toBe(3);
		expect(vectorStore.removeFile).toHaveBeenCalledWith('x.md');
		expect(await manager.renameFile('a.md', 'b.md')).toBe(2);
		expect(vectorStore.renameFile).toHaveBeenCalledWith('a.md', 'b.md');
	});

	it('removeFile / renameFile are no-ops when RAG is disabled', async () => {
		const manager = new RAGManager(makeApp() as any, makeConfig({ enabled: false }), [{ provider: 'openai', apiKey: 'k' }] as any);
		const vectorStore = (manager as any).vectorStore;
		vectorStore.removeFile = jest.fn();
		vectorStore.renameFile = jest.fn();

		expect(await manager.removeFile('x.md')).toBe(0);
		expect(await manager.renameFile('a.md', 'b.md')).toBe(0);
		expect(vectorStore.removeFile).not.toHaveBeenCalled();
		expect(vectorStore.renameFile).not.toHaveBeenCalled();
	});
});
